apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: airflow-webserver
  name: airflow-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      containers:
      - image: apache/airflow:2.1.2-python3.9
        name: webserver
        command: ["airflow", "webserver"]
        env:
          - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
            value: sqlite:////opt/airflow/db/airflow.db
        volumeMounts:
          - name: dags
            mountPath: /opt/airflow/dags
          - name: db
            mountPath: /opt/airflow/db
      - image: apache/airflow:2.1.2-python3.9
        name: schduler
        command: ["airflow", "scheduler"]
        env:
          - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
            value: sqlite:////opt/airflow/db/airflow.db
        volumeMounts:
          - name: dags
            mountPath: /opt/airflow/dags
          - name: db
            mountPath: /opt/airflow/db
      initContainers:
        - image: apache/airflow:2.1.2-python3.9
          name: init-db
          command: [ "airflow", "db", "init"]
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: sqlite:////opt/airflow/db/airflow.db
          volumeMounts:
            - name: db
              mountPath: /opt/airflow/db
        - image: apache/airflow:2.1.2-python3.9
          name: create-user
          command: [ "airflow", "users", "create", "-e", "admin@admin.com", "-f", "admin", "-l", "admin", "-p", "admin", "-r", "Admin", "-u", "admin"]
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: sqlite:////opt/airflow/db/airflow.db
          volumeMounts:
            - name: db
              mountPath: /opt/airflow/db
      volumes:
        - name: db
          emptyDir: {}
        - name: dags
          emptyDir: {}