apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: airflow-webserver
  name: airflow-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      containers:
      - image: apache/airflow:2.1.2-python3.9
        name: webserver
        command: ["airflow", "webserver"]
        env:
          - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
            value: sqlite:////opt/airflow/db/airflow.db
        volumeMounts:
          - name: dags
            mountPath: /opt/airflow/dags
          - name: db
            mountPath: /opt/airflow/db
      - image: apache/airflow:2.1.2-python3.9
        name: schduler
        command: ["airflow", "scheduler"]
        env:
          - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
            value: sqlite:////opt/airflow/db/airflow.db
        volumeMounts:
          - name: dags
            mountPath: /opt/airflow/dags
          - name: db
            mountPath: /opt/airflow/db
      - image: k8s.gcr.io/git-sync/git-sync:v3.3.4
        name: git-sync
        env:
          - name: GIT_SYNC_REPO
            value: https://github.com/DenisOgr/airflow-k8s.git
          - name: GIT_SYNC_BRANCH
            value: master
          - name: GIT_SYNC_DEPTH
            value: '0'
          - name: GIT_SYNC_ROOT
            value: /opt/airflow/dags
          - name: GIT_SYNC_WAIT
            value: '60'
        volumeMounts:
          - name: dags
            mountPath: /opt/airflow/dags
      initContainers:
        - image: apache/airflow:2.1.2-python3.9
          name: init-db
          command: [ "airflow", "db", "init"]
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: sqlite:////opt/airflow/db/airflow.db
          volumeMounts:
            - name: db
              mountPath: /opt/airflow/db
        - image: apache/airflow:2.1.2-python3.9
          name: create-user
          command: [ "airflow", "users", "create", "-e", "admin@admin.com", "-f", "admin", "-l", "admin", "-p", "admin", "-r", "Admin", "-u", "admin"]
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: sqlite:////opt/airflow/db/airflow.db
          volumeMounts:
            - name: db
              mountPath: /opt/airflow/db
      volumes:
        - name: db
          emptyDir: {}
        - name: dags
          emptyDir: {}